# Generated by Django 6.0.2 on 2026-05-27 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_treatment_plan'),
        ('clinical_notes', '0002_clinicalnote_updated_by_clinicalnotehistory'),
        ('clinics', '0001_initial'),
        ('intakes', '0007_alter_intake_submitted_at'),
        ('patients', '0005_alter_patient_clinic'),
        ('treatment_plans', '0003_treatmentplanconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='例: 初回施術、再診、腰痛施術など', max_length=120, verbose_name='セッション名')),
                ('status', models.CharField(choices=[('pending', '準備中'), ('recording', '録音中'), ('uploaded', 'アップロード済み'), ('transcribing', '文字起こし中'), ('summarizing', '要約中'), ('done', '完了'), ('failed', '失敗'), ('canceled', 'キャンセル')], default='pending', max_length=30, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('total_duration_sec', models.PositiveIntegerField(default=0, verbose_name='合計録音秒数')),
                ('transcript_text', models.TextField(blank=True, verbose_name='統合文字起こし')),
                ('transcript_json', models.JSONField(blank=True, default=dict, verbose_name='統合文字起こしJSON')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='AI統合要約')),
                ('confirmed_summary_json', models.JSONField(blank=True, default=dict, verbose_name='確定済み要約')),
                ('summary_status', models.CharField(default='draft', help_text='draft / confirmed など', max_length=30, verbose_name='要約確認状態')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー内容')),
                ('memo', models.TextField(blank=True, verbose_name='スタッフメモ')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='要約確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_session', to='appointments.appointment', verbose_name='予約')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sessions', to='clinics.clinic', verbose_name='院')),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='clinical_notes.clinicalnote', verbose_name='カルテ')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_treatment_sessions', to=settings.AUTH_USER_MODEL, verbose_name='要約確定者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_sessions', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='intakes.intake', verbose_name='Web問診')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sessions', to='patients.patient', verbose_name='患者')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_sessions', to='treatment_plans.treatmentplan', verbose_name='施術計画')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_treatment_sessions', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '施術セッション',
                'verbose_name_plural': '施術セッション',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentSessionChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(default=0, help_text='0始まり。録音順に並べる。', verbose_name='チャンク番号')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='treatment_session_audio/%Y/%m/', verbose_name='音声ファイル')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('duration_sec', models.PositiveIntegerField(default=0, verbose_name='録音秒数')),
                ('transcript_text', models.TextField(blank=True, verbose_name='文字起こし')),
                ('transcript_json', models.JSONField(blank=True, default=dict, verbose_name='文字起こしJSON')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='チャンク要約')),
                ('status', models.CharField(choices=[('pending', '準備中'), ('uploaded', 'アップロード済み'), ('transcribing', '文字起こし中'), ('summarized', '要約済み'), ('failed', '失敗')], default='pending', max_length=30, verbose_name='ステータス')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='追加情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='treatment_sessions.treatmentsession', verbose_name='施術セッション')),
            ],
            options={
                'verbose_name': '施術セッションチャンク',
                'verbose_name_plural': '施術セッションチャンク',
                'ordering': ['session', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['clinic', 'created_at'], name='treatment_s_clinic__1ff55d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['clinic', 'status', 'created_at'], name='treatment_s_clinic__4cf891_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['patient', 'created_at'], name='treatment_s_patient_8a919e_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsession',
            index=models.Index(fields=['appointment'], name='treatment_s_appoint_8b17f0_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsessionchunk',
            index=models.Index(fields=['session', 'chunk_index'], name='treatment_s_session_91aa73_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsessionchunk',
            index=models.Index(fields=['session', 'status'], name='treatment_s_session_8e348f_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentsessionchunk',
            index=models.Index(fields=['created_at'], name='treatment_s_created_8974bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentsessionchunk',
            constraint=models.UniqueConstraint(fields=('session', 'chunk_index'), name='unique_treatment_session_chunk_index'),
        ),
    ]
