# Generated by Django 6.0 on 2026-01-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', '待機'), ('processing', '処理中'), ('success', '成功'), ('failed', '失敗')], default='queued', max_length=20)),
                ('input_text', models.TextField(blank=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_jobs', to='clinics.clinic')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_jobs', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='ai_jobs_aud_clinic__66e585_idx'), models.Index(fields=['clinic', 'created_at'], name='ai_jobs_aud_clinic__38f4b5_idx')],
            },
        ),
    ]
