# Generated by Django 6.0 on 2026-01-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiojob',
            name='ai_output_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
