# Generated by Django 6.0 on 2026-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_jobs', '0002_audiojob_ai_output_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiojob',
            name='safety_hits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
