# Generated by Django 6.0.2 on 2026-03-07 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clinical_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClinicalNoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soap_json', models.JSONField(blank=True, default=dict)),
                ('extract_json', models.JSONField(blank=True, default=dict)),
                ('followups_json', models.JSONField(blank=True, default=list)),
                ('web_intake_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_note_histories', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='clinical_notes.clinicalnote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
