# Generated by Django 6.0.2 on 2026-05-29 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_notes', '0002_clinicalnote_updated_by_clinicalnotehistory'),
        ('treatment_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='treatment_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='treatment_sessions.treatmentsession', verbose_name='施術セッション'),
        ),
    ]
