# Generated by Django 6.0 on 2025-12-25 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('draft_ai', 'AI下書き'), ('edited', '編集済み'), ('finalized', '確定')], default='draft_ai', max_length=20)),
                ('subjective_text', models.TextField(blank=True)),
                ('objective_text', models.TextField(blank=True)),
                ('assessment_text', models.TextField(blank=True)),
                ('plan_text', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_notes', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, help_text='作成者（AIの場合は空でもOK）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chart_notes', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_notes', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='charts_char_clinic__4bf4f0_idx'), models.Index(fields=['clinic', 'visit'], name='charts_char_clinic__9763a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('visit', 'version'), name='unique_chartnote_version_per_visit')],
            },
        ),
    ]
