# Generated by Django 6.0 on 2025-12-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('symptom_type', models.CharField(choices=[('acute', '急性'), ('chronic', '慢性'), ('unknown', '不明')], default='unknown', max_length=20)),
                ('onset', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='patients.patient')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['clinic', 'submitted_at'], name='intakes_int_clinic__0222ab_idx'), models.Index(fields=['clinic', 'patient'], name='intakes_int_clinic__9adf70_idx')],
            },
        ),
    ]
