# Generated by Django 6.0 on 2025-12-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Web問診の詳細データ'),
        ),
    ]
