# Generated by Django 6.0 on 2026-02-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0003_interviewrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewrecording',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('pending', '未アップロード'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
