# Generated by Django 6.0 on 2026-02-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('intakes', '0004_alter_interviewrecording_status'),
        ('patients', '0004_alter_patient_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecording',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='intakes.intake'),
        ),
        migrations.AlterField(
            model_name='interviewrecording',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='interviewrecording',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='interviewrecording',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='patients.patient'),
        ),
    ]
