# Generated by Django 6.0.2 on 2026-03-01 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0005_interviewrecording_intake_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecording',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='confirmed_summary_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='summary_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=16),
        ),
    ]
