# Generated by Django 6.0.2 on 2026-03-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakes', '0006_interviewrecording_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
