# Generated by Django 6.0.2 on 2026-06-15 21:41

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='表示用院名')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('booking_description', models.TextField(blank=True, verbose_name='予約画面に表示する説明文')),
                ('business_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='営業開始時刻')),
                ('business_end_time', models.TimeField(default=datetime.time(20, 0), verbose_name='営業終了時刻')),
                ('break_start_time', models.TimeField(blank=True, default=datetime.time(13, 0), null=True, verbose_name='休憩開始時刻')),
                ('break_end_time', models.TimeField(blank=True, default=datetime.time(15, 0), null=True, verbose_name='休憩終了時刻')),
                ('appointment_interval_minutes', models.PositiveSmallIntegerField(choices=[(5, '5分'), (10, '10分'), (15, '15分'), (20, '20分'), (30, '30分'), (60, '60分')], default=30, verbose_name='予約受付単位')),
                ('closed_weekdays', models.JSONField(blank=True, default=list, verbose_name='休診曜日')),
                ('primary_color', models.CharField(default='#1D4ED8', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーコードは #RRGGBB 形式で入力してください。', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='メインカラー')),
                ('secondary_color', models.CharField(default='#0F172A', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーコードは #RRGGBB 形式で入力してください。', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='サブカラー')),
                ('accent_color', models.CharField(default='#16A34A', max_length=7, validators=[django.core.validators.RegexValidator(message='カラーコードは #RRGGBB 形式で入力してください。', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='アクセントカラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic', verbose_name='院')),
            ],
            options={
                'verbose_name': '院設定',
                'verbose_name_plural': '院設定',
            },
        ),
    ]
