# Generated by Django 6.0.2 on 2026-06-15 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinicsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='メニュー名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('price', models.PositiveIntegerField(default=0, help_text='税込または院内運用に合わせた表示用料金です。', validators=[django.core.validators.MinValueValidator(0)], verbose_name='料金')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='所要時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_menus', to='clinics.clinic', verbose_name='院')),
            ],
            options={
                'verbose_name': '施術メニュー',
                'verbose_name_plural': '施術メニュー',
                'ordering': ('display_order', 'name', 'id'),
            },
        ),
    ]
