# Generated by Django 6.0.2 on 2026-06-16 11:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_treatment_plan'),
        ('clinical_notes', '0003_clinicalnote_treatment_session'),
        ('clinics', '0003_treatmentmenu'),
        ('patients', '0005_alter_patient_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='施術日')),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('card', 'カード'), ('qr', 'QR決済'), ('bank_transfer', '銀行振込'), ('other', 'その他')], default='cash', max_length=20, verbose_name='支払方法')),
                ('status', models.CharField(choices=[('unpaid', '未払い'), ('paid', '支払い済み'), ('canceled', 'キャンセル')], default='paid', max_length=20, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='appointments.appointment', verbose_name='予約')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='clinics.clinic', verbose_name='院')),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='clinical_notes.clinicalnote', verbose_name='カルテ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='patients.patient', verbose_name='患者')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('treatment_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='clinics.treatmentmenu', verbose_name='施術メニュー')),
            ],
            options={
                'verbose_name': '売上実績',
                'verbose_name_plural': '売上実績',
                'ordering': ('-treatment_date', '-created_at', '-id'),
                'indexes': [models.Index(fields=['clinic', 'treatment_date'], name='clinics_sal_clinic__76ba9e_idx'), models.Index(fields=['clinic', 'status'], name='clinics_sal_clinic__f20f9e_idx'), models.Index(fields=['clinic', 'payment_method'], name='clinics_sal_clinic__57ef21_idx')],
            },
        ),
    ]
