# Generated by Django 6.0.2 on 2026-06-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_salesrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='勤務開始')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='勤務終了')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='休憩開始')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='休憩終了')),
                ('status', models.CharField(choices=[('working', '勤務'), ('off', '休み'), ('half_day', '半休'), ('training', '研修'), ('other', 'その他')], default='working', max_length=20, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='clinics.clinic', verbose_name='院')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_shifts', to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'スタッフシフト',
                'verbose_name_plural': 'スタッフシフト',
                'ordering': ('date', 'staff__last_name', 'staff__first_name', 'staff__username'),
                'indexes': [models.Index(fields=['clinic', 'date'], name='clinics_sta_clinic__7114f4_idx'), models.Index(fields=['clinic', 'staff', 'date'], name='clinics_sta_clinic__b5b97c_idx'), models.Index(fields=['clinic', 'status'], name='clinics_sta_clinic__be0aab_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'staff', 'date'), name='unique_staff_shift_per_clinic_staff_date')],
            },
        ),
    ]
