# Generated by Django 6.0.2 on 2026-06-16 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_staffshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('paid_leave', '有給'), ('morning_off', '午前休'), ('afternoon_off', '午後休'), ('absence', '欠勤'), ('training', '研修'), ('other', 'その他')], default='paid_leave', max_length=30, verbose_name='休暇種別')),
                ('start_date', models.DateField(db_index=True, verbose_name='開始日')),
                ('end_date', models.DateField(db_index=True, verbose_name='終了日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('status', models.CharField(choices=[('requested', '申請中'), ('approved', '承認済み'), ('rejected', '却下'), ('canceled', '取消')], default='requested', max_length=20, verbose_name='ステータス')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='理由')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_leaves', to='clinics.clinic', verbose_name='院')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_leaves', to=settings.AUTH_USER_MODEL, verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'スタッフ休暇',
                'verbose_name_plural': 'スタッフ休暇',
                'ordering': ('-start_date', '-created_at', '-id'),
                'indexes': [models.Index(fields=['clinic', 'start_date', 'end_date'], name='clinics_sta_clinic__af7b2c_idx'), models.Index(fields=['clinic', 'staff', 'start_date'], name='clinics_sta_clinic__74812c_idx'), models.Index(fields=['clinic', 'leave_type'], name='clinics_sta_clinic__35104d_idx'), models.Index(fields=['clinic', 'status'], name='clinics_sta_clinic__fa560d_idx')],
            },
        ),
    ]
