# Generated by Django 6.0.2 on 2026-06-21 00:35

import apps.clinics.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_treatment_plan'),
        ('clinical_notes', '0003_clinicalnote_treatment_session'),
        ('clinics', '0006_staffleave'),
        ('patients', '0005_alter_patient_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('aftercare_report', '施術後説明レポート'), ('posture_report', '姿勢評価レポート'), ('treatment_plan', '施術計画'), ('booking', '予約'), ('other', 'その他')], default='aftercare_report', max_length=30, verbose_name='共有目的')),
                ('token', models.CharField(default=apps.clinics.models.generate_patient_share_token, editable=False, max_length=64, unique=True, verbose_name='共有トークン')),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.clinics.models.default_patient_share_expiry, verbose_name='有効期限')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最終アクセス日時')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='アクセス回数')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_share_tokens', to='appointments.appointment', verbose_name='予約')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_share_tokens', to='clinics.clinic', verbose_name='院')),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_share_tokens', to='clinical_notes.clinicalnote', verbose_name='カルテ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_share_tokens', to=settings.AUTH_USER_MODEL, verbose_name='発行者')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '患者向け共有トークン',
                'verbose_name_plural': '患者向け共有トークン',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['clinic', 'purpose', 'is_active'], name='clinics_pat_clinic__5fee8f_idx'), models.Index(fields=['clinic', 'clinical_note', 'purpose'], name='clinics_pat_clinic__052916_idx')],
            },
        ),
    ]
