# Generated by Django 6.0.2 on 2026-05-27 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_treatment_plan'),
        ('clinics', '0001_initial'),
        ('intakes', '0007_alter_intake_submitted_at'),
        ('patients', '0005_alter_patient_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAiPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, default='スタンダード', max_length=100, verbose_name='プラン名')),
                ('monthly_base_fee', models.PositiveIntegerField(default=50000, help_text='月額基本料金。例: 50000', verbose_name='月額基本料金')),
                ('included_minutes', models.PositiveIntegerField(default=1000, help_text='月額内に含まれるAI録音・文字起こし分数。', verbose_name='月内込み利用分数')),
                ('overage_unit_minutes', models.PositiveIntegerField(default=100, help_text='超過課金の単位。例: 100分ごと', verbose_name='超過課金単位分数')),
                ('overage_unit_price', models.PositiveIntegerField(default=2000, help_text='超過課金単位ごとの金額。例: 100分ごとに2000円', verbose_name='超過課金単価')),
                ('warning_threshold_percent', models.PositiveIntegerField(default=80, help_text='利用量が何%に達したら警告するか。例: 80', verbose_name='警告しきい値')),
                ('danger_threshold_percent', models.PositiveIntegerField(default=90, help_text='利用量が何%に達したら強めの警告を出すか。例: 90', verbose_name='危険しきい値')),
                ('hard_limit_minutes', models.PositiveIntegerField(default=1500, help_text='この分数を超えた場合、AI録音・要約を停止する目安。', verbose_name='強制停止分数')),
                ('is_ai_enabled', models.BooleanField(default=True, verbose_name='AI機能有効')),
                ('allow_overage', models.BooleanField(default=True, help_text='Falseの場合、込み分数を超えた時点でAI利用を制限する。', verbose_name='超過利用を許可')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan', to='clinics.clinic', verbose_name='院')),
            ],
            options={
                'verbose_name': '院別AI契約設定',
                'verbose_name_plural': '院別AI契約設定',
            },
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('stt', '文字起こし'), ('summary', 'AI要約'), ('soap', 'SOAP生成'), ('treatment_plan', '施術計画生成'), ('posture', '姿勢分析'), ('other', 'その他')], default='other', max_length=50, verbose_name='利用種別')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗'), ('skipped', 'スキップ')], default='success', max_length=20, verbose_name='処理結果')),
                ('model_name', models.CharField(blank=True, help_text='例: gpt-4.1-mini, whisper-1 など', max_length=100, verbose_name='AIモデル名')),
                ('audio_duration_sec', models.PositiveIntegerField(default=0, verbose_name='音声時間 秒')),
                ('transcript_chars', models.PositiveIntegerField(default=0, verbose_name='文字起こし文字数')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='入力トークン数')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='出力トークン数')),
                ('estimated_cost_yen', models.PositiveIntegerField(default=0, help_text='OpenAI等のAPI原価の概算。顧客への請求額ではない。', verbose_name='推定AI原価 円')),
                ('billing_minutes', models.PositiveIntegerField(default=0, help_text='音声秒数を切り上げた請求対象分数。例: 61秒なら2分。', verbose_name='請求対象分数')),
                ('error_message', models.TextField(blank=True, verbose_name='エラー内容')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='処理ID、chunk番号、APIレスポンス情報などを保存。', verbose_name='追加情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='appointments.appointment', verbose_name='予約')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to='clinics.clinic', verbose_name='院')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='intakes.intake', verbose_name='Web問診')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='patients.patient', verbose_name='患者')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='intakes.interviewrecording', verbose_name='AI録音')),
            ],
            options={
                'verbose_name': 'AI利用ログ',
                'verbose_name_plural': 'AI利用ログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='ai_usage_ai_clinic__c66686_idx'), models.Index(fields=['clinic', 'usage_type', 'created_at'], name='ai_usage_ai_clinic__a7084d_idx'), models.Index(fields=['patient', 'created_at'], name='ai_usage_ai_patient_5d7ab8_idx'), models.Index(fields=['appointment', 'created_at'], name='ai_usage_ai_appoint_40013f_idx'), models.Index(fields=['recording', 'created_at'], name='ai_usage_ai_recordi_315872_idx')],
            },
        ),
    ]
