# Generated by Django 6.0 on 2026-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='card_no',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
