# Generated by Django 6.0.2 on 2026-06-01 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_treatment_plan'),
        ('clinical_notes', '0003_clinicalnote_treatment_session'),
        ('clinics', '0001_initial'),
        ('patients', '0005_alter_patient_clinic'),
        ('treatment_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='AI姿勢分析', max_length=120)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('analyzed', 'AI分析済み'), ('confirmed', '確定済み'), ('failed', '失敗')], db_index=True, default='draft', max_length=30)),
                ('memo', models.TextField(blank=True, default='', help_text='撮影時の補足メモ。例：右膝痛、バスケ後に痛みなど')),
                ('ai_summary_json', models.JSONField(blank=True, default=dict)),
                ('confirmed_summary_json', models.JSONField(blank=True, default=dict)),
                ('ai_model_name', models.CharField(blank=True, default='', max_length=100)),
                ('ai_error_message', models.TextField(blank=True, default='')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_assessments', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_assessments', to='clinics.clinic')),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_assessments', to='clinical_notes.clinicalnote')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_posture_assessments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posture_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_assessments', to='patients.patient')),
                ('treatment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_assessments', to='treatment_sessions.treatmentsession')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_posture_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostureAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_summary_json', models.JSONField(blank=True, default=dict)),
                ('confirmed_summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='posture_assessments.postureassessment')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posture_assessment_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostureAssessmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('front', '正面'), ('side_right', '右側面'), ('side_left', '左側面'), ('back', '背面'), ('other', 'その他')], db_index=True, max_length=30)),
                ('image', models.ImageField(upload_to='posture/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='posture/thumbs/%Y/%m/')),
                ('ai_image', models.ImageField(blank=True, null=True, upload_to='posture/ai/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posture_assessments.postureassessment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_posture_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='postureassessment',
            index=models.Index(fields=['clinic', 'patient', 'status'], name='posture_ass_clinic__94f5d8_idx'),
        ),
        migrations.AddIndex(
            model_name='postureassessment',
            index=models.Index(fields=['clinic', 'created_at'], name='posture_ass_clinic__e7aee9_idx'),
        ),
        migrations.AddIndex(
            model_name='postureassessmentimage',
            index=models.Index(fields=['assessment', 'image_type'], name='posture_ass_assessm_89dbf5_idx'),
        ),
    ]
