# Generated by Django 6.0.2 on 2026-06-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture_assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postureassessment',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('analyzing', 'AI分析中'), ('analyzed', 'AI分析済み'), ('confirmed', '確定済み'), ('failed', '失敗')], db_index=True, default='draft', max_length=30),
        ),
    ]
