# Generated by Django 6.0.2 on 2026-06-06 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0005_alter_patient_clinic'),
        ('posture_assessments', '0002_alter_postureassessment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='姿勢Before/After比較', max_length=120)),
                ('status', models.CharField(choices=[('draft', '下書き'), ('analyzing', 'AI比較中'), ('analyzed', 'AI比較済み'), ('confirmed', '確定済み'), ('failed', '失敗')], db_index=True, default='draft', max_length=30)),
                ('memo', models.TextField(blank=True, default='', help_text='比較時の補足メモ。例：初回施術前後、1か月後比較など')),
                ('comparison_json', models.JSONField(blank=True, default=dict, help_text='角度差・左右差・画像比較などの構造化データ')),
                ('ai_summary_json', models.JSONField(blank=True, default=dict, help_text='AI比較分析の結果')),
                ('confirmed_summary_json', models.JSONField(blank=True, default=dict, help_text='施術者が確定した比較結果')),
                ('ai_model_name', models.CharField(blank=True, default='', max_length=100)),
                ('ai_error_message', models.TextField(blank=True, default='')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('after_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_comparisons', to='posture_assessments.postureassessment')),
                ('before_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_comparisons', to='posture_assessments.postureassessment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_comparisons', to='clinics.clinic')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_posture_comparisons', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_posture_comparisons', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posture_comparisons', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_posture_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'patient', 'status'], name='posture_ass_clinic__62b5e5_idx'), models.Index(fields=['clinic', 'created_at'], name='posture_ass_clinic__42a26f_idx')],
            },
        ),
    ]
