# Generated by Django 6.0.2 on 2026-06-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posture_assessments', '0003_posturecomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='postureassessmentimage',
            name='annotated_image',
            field=models.ImageField(blank=True, help_text='姿勢ラインや角度を描画した画像', null=True, upload_to='posture/annotated/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='postureassessmentimage',
            name='landmarks_json',
            field=models.JSONField(blank=True, default=dict, help_text='耳・肩・骨盤・膝・足首などの座標情報'),
        ),
        migrations.AddField(
            model_name='postureassessmentimage',
            name='measurements_json',
            field=models.JSONField(blank=True, default=dict, help_text='角度・左右差・前方位などの計測値'),
        ),
    ]
