# Generated by Django 6.0.2 on 2026-03-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
        ('clinical_notes', '0002_clinicalnote_updated_by_clinicalnotehistory'),
        ('intakes', '0007_alter_intake_submitted_at'),
        ('patients', '0004_alter_patient_card_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='計画タイトル')),
                ('chief_complaint', models.CharField(blank=True, max_length=255, verbose_name='主訴')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='次回来院日')),
                ('visit_guide_type', models.CharField(blank=True, choices=[('daily', '毎日'), ('weekly', '週'), ('monthly', '月'), ('custom', '個別設定')], max_length=20, verbose_name='来院目安区分')),
                ('visit_guide_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='来院回数目安')),
                ('visit_guide_unit_note', models.CharField(blank=True, max_length=100, verbose_name='来院目安補足')),
                ('bath_instruction', models.TextField(blank=True, verbose_name='入浴について')),
                ('walking_instruction', models.TextField(blank=True, verbose_name='歩行について')),
                ('exercise_instruction', models.TextField(blank=True, verbose_name='運動について')),
                ('work_instruction', models.TextField(blank=True, verbose_name='就労について')),
                ('lifestyle_other_instruction', models.TextField(blank=True, verbose_name='日常生活その他')),
                ('caution_notes', models.TextField(blank=True, verbose_name='その他注意事項')),
                ('expected_recovery_weeks_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='改善目安（最短週）')),
                ('expected_recovery_weeks_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='改善目安（最長週）')),
                ('rebound_reaction_note', models.TextField(blank=True, verbose_name='好転反応の説明')),
                ('explained_to_patient', models.BooleanField(default=False, verbose_name='患者へ説明済み')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効な計画')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='appointments.appointment', verbose_name='関連予約')),
                ('clinical_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='clinical_notes.clinicalnote', verbose_name='関連カルテ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_plans', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='intakes.intake', verbose_name='関連問診')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '施術計画',
                'verbose_name_plural': '施術計画',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='施術日')),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='痛みレベル')),
                ('symptom_change', models.TextField(blank=True, verbose_name='症状変化')),
                ('adl_status', models.TextField(blank=True, verbose_name='ADL・生活状況')),
                ('treatment_detail', models.TextField(blank=True, verbose_name='施術内容')),
                ('post_treatment_response', models.TextField(blank=True, verbose_name='施術後の反応')),
                ('next_instruction', models.TextField(blank=True, verbose_name='次回までの指示')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_progresses', to=settings.AUTH_USER_MODEL, verbose_name='記録者')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='treatment_plans.treatmentplan', verbose_name='施術計画')),
            ],
            options={
                'verbose_name': '施術経過記録',
                'verbose_name_plural': '施術経過記録',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
