# Generated by Django 6.0.2 on 2026-03-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('active', '進行中'), ('completed', '完了'), ('paused', '中断')], default='active', max_length=20, verbose_name='計画ステータス'),
        ),
    ]
