# Generated by Django 6.0.2 on 2026-05-24 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_clinic'),
        ('treatment_plans', '0002_treatmentplan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlanConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_name', models.CharField(blank=True, max_length=100, verbose_name='署名者名')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='treatment_plan_signatures/%Y/%m/', verbose_name='署名画像')),
                ('plan_snapshot', models.JSONField(blank=True, default=dict, verbose_name='署名時点の施術計画')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='署名日時')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan_consents', to='patients.patient', verbose_name='患者')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='treatment_plans.treatmentplan', verbose_name='施術計画同意')),
                ('signed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_treatment_plan_consents', to=settings.AUTH_USER_MODEL, verbose_name='署名ユーザー')),
            ],
            options={
                'verbose_name': '施術計画同意',
                'verbose_name_plural': '施術計画同意',
                'ordering': ['-signed_at'],
            },
        ),
    ]
