# Generated by Django 6.0.2 on 2026-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', '問診待ち'), ('booked', '予約確定'), ('arrived', '来院'), ('completed', '完了'), ('cancelled', 'キャンセル'), ('no_show', '無断キャンセル')], default='pending', max_length=20),
        ),
    ]
