# Generated by Django 6.0.2 on 2026-03-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
        ('treatment_plans', '0002_treatmentplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='treatment_plans.treatmentplan', verbose_name='関連施術計画'),
        ),
    ]
