# Generated by Django 6.0 on 2025-12-25 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('intakes', '0002_alter_intake_payload'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('done', '完了')], default='in_progress', max_length=20)),
                ('pain_scale_before', models.PositiveSmallIntegerField(blank=True, help_text='施術前PS（0-10）', null=True)),
                ('pain_scale_after', models.PositiveSmallIntegerField(blank=True, help_text='施術後PS（0-10）', null=True)),
                ('next_visit_suggestion', models.CharField(blank=True, help_text='次回来院の目安（例：2〜3日後）', max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinics.clinic')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='intakes.intake')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('practitioner', models.ForeignKey(blank=True, help_text='施術者（担当）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_as_practitioner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at', '-created_at'],
                'indexes': [models.Index(fields=['clinic', 'visited_at'], name='visits_visi_clinic__c2f437_idx'), models.Index(fields=['clinic', 'status'], name='visits_visi_clinic__9a5362_idx'), models.Index(fields=['clinic', 'patient'], name='visits_visi_clinic__a9a0d5_idx')],
            },
        ),
    ]
